Add HTTPS/Basic auth support
prometheus/pushgateway pull request #381
Opened 2021-01-05 16:34 UTC by roidelapluie

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

2021-01-05 16:45 UTC, beorn7 approved these changes
Just documentation nits. 

Very awesome. Please merge once you have addressed my nits one way or the other.

2021-01-05 17:07 UTC, roidelapluie commented
I have added a sentence to clarify that everything is protected by the TLS/Basic auth, including scrape and UI, and not only pushing metrics.

2021-01-05 22:48 UTC, beorn7 requested changes
Thanks for the doc tweaks. Which inspired me to tweak them even more. (o:

2021-01-05 22:48 UTC, beorn7 commented on README.md
> +control of the API's.
If I may continue my nitpicking: API's → APIs.

However, the `/metrics` endpoint is not really an API, is it? How about "This enables better control of the various HTTP endpoints."

2021-01-05 22:48 UTC, beorn7 commented on README.md
> +push metrics, the /metrics endpoint used by Prometheus and the web UI.
Various nits here. My suggestion:

Note that the TLS and basic authentication settings affect all HTTP endpoints: `/metrics` for scraping, the API to push metrics via `/metrics/...`, the admin API via `/api/...`, and the web UI.

2021-01-05 23:58 UTC, roidelapluie commented
Awesome, applied!

2021-01-06 11:28 UTC, beorn7 approved these changes

2021-01-06 11:28 UTC, merged