Release v1.4.3
prometheus/pushgateway pull request #471
Opened 2022-05-28 16:58 UTC by beorn7

This release merely updates dependencies and, as a byproduct, the binaries that come with the release will be built with the current Go version (1.18.x).

The last release is quite long ago, and a lot of security issues have accumulated in depencies and the Go version used to build the binaries of the previous release. I do not now of any issues relevant to the Pushgateway, but at this point, it's probably better to cut a new release to avoid false alerts (and maybe even avoid an issue we don't know about yet). It comes with the risk of pulling in new bugs, though.

2022-05-28 17:11 UTC, beorn7 commented
Sorry for weekend PR. I set the release date to Monday. Feel free to review when the weekend is over.

2022-05-28 17:13 UTC, beorn7 commented
Fixes #469.

2022-05-30 12:48 UTC, SuperQ requested changes
I would recommend changing the minimum Go version in go.mod to 1.17 and running a go mod tidy to get the new indirect dependency format.

2022-05-30 12:48 UTC, SuperQ commented on .circleci/config.yml
> +      - image: quay.io/prometheus/golang-builder:1.18-base
We're actually switching these over to `cimg/go:1.18` except for `prometheus/prometheus`.

2022-05-30 13:32 UTC, beorn7 commented
Both comments addressed. Thank you very much. PHAL.

2022-05-30 15:19 UTC, SuperQ approved these changes
LGTM

2022-05-30 15:24 UTC, roidelapluie approved these changes

2022-05-30 18:53 UTC, merged