Update deps and cut v1.6.1
prometheus/pushgateway pull request #571
Opened 2023-09-05 16:55 UTC by beorn7

2023-09-05 17:03 UTC, beorn7 commented
Fixes #569 .

2023-09-05 22:24 UTC, SuperQ requested changes
My Go mod version check script says we need `go 1.19` in go.mod.

2023-09-06 11:45 UTC, beorn7 commented
Done. PHAL.

2023-09-06 12:04 UTC, SuperQ approved these changes

2023-09-06 12:15 UTC, merged