Keep record of unwinded containers on page refresh
prometheus/pushgateway pull request #581
Opened 2023-10-02 16:42 UTC by ResamVi

The solution retains a record of the currently un-collapsed container and unwinds it on a page refresh.
No extra refresh button and no live-update. 

The minor inconvenience of this solution is that on a page refresh the unwind animation plays.

[Screencast from 2023-10-02 18-40-31.webm](https://github.com/prometheus/pushgateway/assets/6261556/f0ac6de7-0364-425e-a947-81d4a737fcaa)

Helps #568

2023-10-02 16:45 UTC, ResamVi commented
@beorn7 would you have a look?

2023-10-03 19:51 UTC, beorn7 commented
On my list.

2023-10-08 13:39 UTC, beorn7 commented
I think this is quite good for a start.

But maybe we should use the session storage rather than the local storage? A user might open different windows with different views on the same PGW. Also, it might confusing if you come back to the PGW UI after some time and get elements expanded because they are still persisted in your local storage. You might also get garbage left behind, maybe even leading to multiple elements getting expanded on reload.

2023-10-09 08:24 UTC, ResamVi commented
You're right, I replaced it with `sessionStorage` now

2023-10-14 18:28 UTC, beorn7 requested changes
Thank you. I think this will work as intended.

However, you need to run `make assets` and commit the results to bake the changes into the Go binary.

2023-10-16 10:49 UTC, ResamVi commented
> However, you need to run `make assets` and commit the results to bake the changes into the Go binary.

Alright, done. 

Thansk, I appreciate the guidance and your time in reviewing this 🙂

2023-10-17 16:41 UTC, beorn7 approved these changes
Thank you very much.

2023-10-17 16:42 UTC, merged