Optimize computeRoutePrefix
prometheus/pushgateway pull request #584
Opened 2023-10-07 17:39 UTC by donuts-are-good

Previously, computeRoutePrefix was adding a '/' to the start of the prefix and then removing it from the end, regardless of whether it was there or not. This resulted in unnecessary string operations. The updated function only adds or removes the '/' when necessary, improving efficiency. Additionally, the function now uses strings.HasPrefix and strings.HasSuffix for clearer intent and readability.

2023-10-08 14:23 UTC, beorn7 commented
Thank you. I'll have a look ASAP. Could you fix the gofmt issue flagged by the CI test in the meantime?

2023-10-08 15:10 UTC, donuts-are-good commented
Good morning @beorn7, and thank you for the reply. I will do that when I return to my desk this afternoon after family time :)

2023-10-09 17:13 UTC, donuts-are-good commented
Bit embarrassed to ask, but what is it that is needed here?

![image](https://github.com/prometheus/pushgateway/assets/96031819/d814a932-e092-4cd0-846f-54a9d5675068)

2023-10-09 19:02 UTC, beorn7 commented
Maybe you are using an old Go version?

Line 10 is a spurious blank line.

2023-10-10 20:20 UTC, donuts-are-good commented
Yahtzee!

2023-10-12 18:43 UTC, donuts-are-good commented
Is there anything else I should do, or just sit tight and wait?

2023-10-14 17:09 UTC, beorn7 requested changes
Thank you. Looks good in general, but L263 isn't needed, and I have some Promethean nit picking about punctuation. See comments.

Apologies for the review delay. I generally have to fight a lengthy review backlog, and on top of that, I have been at SREcon all week long.

2023-10-14 17:09 UTC, beorn7 commented on main.go
> +		prefix = strings.TrimSuffix(prefix, "/")
If you look at the [source code of `strings.TrimSuffix`](https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/strings/strings.go;l=1052), the first line in the function is literary `if HasSuffix(s, suffix) {`, so you don't really need L263 here.

2023-10-15 14:57 UTC, donuts-are-good commented
> Thank you. Looks good in general, but L263 isn't needed, and I have some Promethean nit picking about punctuation. See comments.
> 
> Apologies for the review delay. I generally have to fight a lengthy review backlog, and on top of that, I have been at SREcon all week long.

Sounds good, I'll get this taken care of early this week. Hope it was a good trip, thanks for the feedback :)

2023-10-19 23:32 UTC, donuts-are-good commented on main.go
> +	// Ensure prefix starts with "/"
No worries

2023-10-19 23:33 UTC, donuts-are-good commented on main.go
> +	// Ensure prefix starts with "/"
Resolved in [a59285c](https://github.com/prometheus/pushgateway/pull/584/commits/a59285c77447922391957cd64c3d82f24aabfa62)

2023-10-21 14:39 UTC, beorn7 approved these changes

2023-10-21 14:39 UTC, merged

2023-10-21 19:42 UTC, donuts-are-good commented
What an awesome gift to see when I log in to Github today. Thank you for your time and guidance on this PR @beorn7