Add UTF-8 support in metric and label names
prometheus/pushgateway pull request #689
Opened 2024-09-12 15:47 UTC by fedetorres93

As part of the [initiative for adding UTF-8 support to Prometheus](https://github.com/prometheus/prometheus/issues/13095), this PR brings UTF-8 support for metric and label names as described in [this proposal](https://github.com/prometheus/proposals/blob/main/proposals/2023-08-21-utf8.md) (for example: `{"metric.name", "label.name"="value"}`.

For UTF-8 label names defined in the URL path, [an escaping syntax](https://github.com/prometheus/proposals/blob/main/proposals/2023-08-21-utf8.md#text-escaping) is used. For example, the label `"label.name"="value"` would be escaped like: `/metrics/job/example/U__label_2e_name/value`. This escaping is compatible with the base64 encoding for label values: `/metrics/job/example/U__label_2e_name@base64/dmFsdWU=`

UTF-8 support can be enabled by running the Pushgateway with the flag `--push.enable-escaped-labels=true  `

2024-09-18 16:23 UTC, beorn7 commented
Sorry, still fighting my backlog. I hope I get to review this tomorrow.

2024-09-20 13:43 UTC, beorn7 requested changes
Thank you for doing this.
A few ideas about how to precisely control whether to escape or not. I hope I got it right, but happy to learn where I'm wrong.

In different news, this needs documentation (which currently is just in the ever growing README.md – feel free to add it there, breaking down the documentation into "proper" documentation files would be a task for another PR).

2024-09-20 13:43 UTC, beorn7 commented on handler/handler_test.go
> +	"github.com/prometheus/common/model"
This has to go into the next block (line 29).

2024-09-20 13:43 UTC, beorn7 commented on main.go
> +	"github.com/prometheus/common/model"
As above, has to go to line 39 or so.

2024-09-20 13:43 UTC, beorn7 commented on main.go
> +		pushEscaped         = app.Flag("push.enable-escaped-labels", "Allow escaped characters in label names in URLs.").Default("false").Bool()
Let's call this `push.enable-utf8-names` to mirror the feature flag in Prometheus, and also to correctly describe what we are doing. (Without the flag, the PGW will reject non-legacy characters in names even in the payload of a push.)
Variable name and doc string has to be adjusted accordingly.

2024-09-20 13:43 UTC, beorn7 commented on main.go
> +		model.NameValidationScheme = model.UTF8Validation
Let's explicitly set `model.LegacyValidation` if the flag is not set (to defend against a change of the default in prometheus/client_model).

2024-09-20 13:43 UTC, beorn7 commented on handler/push.go
> +		unescapedName := model.UnescapeName(trimmedName, model.ValueEncodingEscaping)
We don't even want to try to unescape if the corresponding flag is not set. To not refer to the flag value directly here, maybe set a package-level variable of type `model.EscapingScheme` to either `model.ValueEncodingEscaping` or `model.NoEscaping` and then use that variable here.

2024-09-20 13:43 UTC, beorn7 commented on handler/push.go
> +			!model.LabelName(unescapedName).IsValid() ||
With this validity test, wo don't need the one in the previous line anymore, do wo?

2024-09-23 21:52 UTC, fedetorres93 commented
@beorn7 Thanks for your feedback, the requested changes were addressed.

2024-09-25 16:19 UTC, beorn7 requested changes
Code looks good (modulu doc comment on `push.EscapingScheme`. But we also need documentation. (As suggested previously, I believe it is OK for now to add a section to the ever growing README.md, keeping in mind that eventually we would like to break it up into "proper" documentation.)

2024-09-25 16:19 UTC, beorn7 commented on handler/push.go
> +var EscapingScheme = model.NoEscaping
This could benefit from a doc comment.

2024-09-25 21:36 UTC, fedetorres93 commented
@beorn7 Sorry about the documentation, thanks for pointing it out, now it's added. Also added `EscapingScheme` comment.

2024-09-26 17:43 UTC, beorn7 requested changes
Cool. I just couldn't resist and applied a lot of wordsmithing. Please see my suggestions.

2024-09-26 17:43 UTC, beorn7 commented on README.md
> +For UTF-8 label names defined in the URL path, [an escaping syntax](https://github.com/prometheus/proposals/blob/main/proposals/2023-08-21-utf8.md#text-escaping) is used.
I would not explain the syntax of the text exposition format here. (It also doesn't cover protobuf.)

With some wordsmithing included, I would propose the following:

```suggestion
Newer versions of the Prometheus exposition formats (text and protobuf)
support the full UTF-8 character set in metric and label names. The
Pushgateway only accepts special characters in names if the command line
flag `--push.enable-utf8-names` is set.

To allow special characters in label names that are part of the URL path, the flag also enables a 
[specific encoding mechanism](https://github.com/prometheus/proposals/blob/main/proposals/2023-08-21-utf8.md#text-escaping). This is similar to the base64 encoding for label _values_ described above,
but works differently in detail for technical and historical reasons. As before, client libraries
should usually take care of the encoding. It works as follows:
```

2024-09-26 17:43 UTC, beorn7 commented on README.md
> +* If a string should start with "U__" already, it will need to be escaped: `U___55_____`. (That's `U__` + `_55_` (for `U`) + `__` + `__`).
Let's stay consistent with regard to the form. You start with an imperative form and then use future tense.

Here my suggestion with a few things added:

```suggestion
* A label name containing encoded characters starts with `U__`.
* All non-standard characters (i.e. characters other than letters, numbers, and underscores) are encoded as underscores surrounding their Unicode value, like `_1F60A_`.
* All pre-existing underscores are encoded as a double-underscore: `__`.
* If a label name starts with `U__` already, these characters have to be encoded as well, resulting in `U___55_____`. (That's `U__` + `_55_` (for `U`) + `__` + `__`).
* A label name starting with `U__` in it's encoded form, but containing invalid sequences (e.g. `U__in_xxx_valid`) is left unchanged.
```

2024-09-26 17:43 UTC, beorn7 commented on README.md
> +For example, the label `"foo.bar"="baz"` would be escaped like:
Let's better use "encoded" rather than "escaped" to only use one word throughout this file.

2024-09-26 17:43 UTC, beorn7 commented on README.md
> +This escaping is compatible with the base64 encoding for label values:
escaping → encoding, see above.

2024-09-26 17:43 UTC, beorn7 commented on README.md
> +
Let's add something about the one edge case, e.g.

Note that this method has an unlikely edge case that is not handled properly: A pusher unaware of the encoding mechanism might use a label name that is _also_ a valid encoded version of another label name. E.g. if a pusher intends to use the label name `U__foo_2e_bar`, but doesn't encode it as `U___55_____foo__2e__bar`, the Pushgateway will decode `U__foo_2e_bar` to `foo.bar`. This is the main reason why the decoding is opt-in via the `--push.enable-utf8-names` flag.

2024-09-27 14:47 UTC, fedetorres93 commented
@beorn7 Thanks for the docs suggestions, done.

2024-10-02 15:48 UTC, beorn7 approved these changes
:ship:

2024-10-02 15:52 UTC, merged